apiVersion: v1
kind: Service
metadata:
  name:  cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
  - name:  cart
    protocol: TCP
    port:  82
    targetPort:  4003
    nodePort: 30003