apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: nabeelncz/services-user:0.0.2
        name: user