apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mongodb
  template:
    metadata:
      labels:
        app: user-mongodb
    spec:
      containers:
        - name:  user-mongodb
          image:  mongo:latest
          