apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: nabeelncz/services-order:0.0.2
        name: order