apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-mongodb
  template:
    metadata:
      labels:
        app: order-mongodb
    spec:
      containers:
        - name:  order-mongodb
          image:  mongo:latest
          