version: '3'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_user
    depends_on:
      - mongodb
    ports:
      - "4001:4001"

  mongodb:
    image: mongo:latest
    container_name: app_mongodb
    ports:
      - "27017:27017"